/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import ComunicationOCC.ClientOCC;
import ComunicationOCC.ServerOCC;
import java.awt.Color;

import java.io.IOException;

import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * @author Antonio Ramos 
           Miguel Silva
 */
public class OCC extends javax.swing.JFrame {

    /**
     * Creates new form OIS
     */
    private static int N_Customers; // [1,99] default 10
    private static int cto;
    private static String som;
    private static int sto;
    private static String Message;
    private static String[] ST_Customer;
    private static String ST_Cashier;
    private static String ST_Manager;
    private static String messageButton;

    public OCC() {
        initComponents();
        state_info.setVisible(false);
        aviso.setVisible(false);
        permitButton.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        occ_label = new javax.swing.JLabel();
        n_costumers_label = new javax.swing.JLabel();
        ncustomers = new javax.swing.JTextField();
        movement_label = new javax.swing.JLabel();
        timeOut_Customers = new javax.swing.JComboBox<>();
        start_b = new javax.swing.JButton();
        suspend_b = new javax.swing.JButton();
        resume_b = new javax.swing.JButton();
        stop_b = new javax.swing.JButton();
        end_b = new javax.swing.JButton();
        Supervisor_label = new javax.swing.JLabel();
        supervisor_value = new javax.swing.JComboBox<>();
        sto_label = new javax.swing.JLabel();
        sto_value = new javax.swing.JComboBox<>();
        aviso = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        state_info = new javax.swing.JPanel();
        Customer_info = new javax.swing.JLabel();
        Manager_info = new javax.swing.JLabel();
        Cashier_info = new javax.swing.JLabel();
        cashier_panel = new javax.swing.JPanel();
        customer_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        manager_panel = new javax.swing.JPanel();
        permitButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        occ_label.setBackground(new java.awt.Color(102, 255, 51));
        occ_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        occ_label.setForeground(new java.awt.Color(51, 153, 0));
        occ_label.setText("    OCC GUI");

        n_costumers_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n_costumers_label.setText("Total Number of customers:");

        movement_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movement_label.setText("Timeout for the movement of each customer:");

        timeOut_Customers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "250", "500", "1000", "0" }));
        timeOut_Customers.setToolTipText("");

        start_b.setBackground(new java.awt.Color(0, 153, 0));
        start_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        start_b.setForeground(new java.awt.Color(255, 255, 255));
        start_b.setText("START");
        start_b.setBorderPainted(false);
        start_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_painel(evt);
            }
        });
        start_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_bActionPerformed(evt);
            }
        });

        suspend_b.setBackground(new java.awt.Color(255, 204, 0));
        suspend_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        suspend_b.setForeground(new java.awt.Color(255, 255, 255));
        suspend_b.setText("SUSPEND");
        suspend_b.setBorderPainted(false);
        suspend_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspend_bActionPerformed(evt);
            }
        });

        resume_b.setBackground(new java.awt.Color(102, 0, 204));
        resume_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resume_b.setForeground(new java.awt.Color(255, 255, 255));
        resume_b.setText("RESUME");
        resume_b.setBorderPainted(false);
        resume_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resume_bActionPerformed(evt);
            }
        });

        stop_b.setBackground(new java.awt.Color(204, 102, 0));
        stop_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stop_b.setForeground(new java.awt.Color(255, 255, 255));
        stop_b.setText("STOP");
        stop_b.setBorderPainted(false);

        end_b.setBackground(new java.awt.Color(204, 0, 0));
        end_b.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        end_b.setForeground(new java.awt.Color(255, 255, 255));
        end_b.setText("END");
        end_b.setBorderPainted(false);
        end_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_bActionPerformed(evt);
            }
        });

        Supervisor_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Supervisor_label.setText("Supervisor Operating Mode:");

        supervisor_value.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manual", "auto" }));

        sto_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sto_label.setText("STO:");

        sto_value.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "100", "2500", "2500", "5000" }));

        aviso.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 51, 51));
        aviso.setText("jLabel1");

        state_info.setBackground(new java.awt.Color(0, 153, 0));
        state_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        state_info.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                client(evt);
            }
        });

        Customer_info.setBackground(new java.awt.Color(255, 255, 255));
        Customer_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Customer_info.setForeground(new java.awt.Color(255, 255, 255));
        Customer_info.setText("Customer");

        Manager_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Manager_info.setForeground(new java.awt.Color(255, 255, 255));
        Manager_info.setText("Manager");

        Cashier_info.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cashier_info.setForeground(new java.awt.Color(255, 255, 255));
        Cashier_info.setText("Cashier");

        javax.swing.GroupLayout cashier_panelLayout = new javax.swing.GroupLayout(cashier_panel);
        cashier_panel.setLayout(cashier_panelLayout);
        cashier_panelLayout.setHorizontalGroup(
            cashier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        cashier_panelLayout.setVerticalGroup(
            cashier_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(26, 26));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(26, 26));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(26, 26));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout customer_panelLayout = new javax.swing.GroupLayout(customer_panel);
        customer_panel.setLayout(customer_panelLayout);
        customer_panelLayout.setHorizontalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        customer_panelLayout.setVerticalGroup(
            customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_panelLayout.createSequentialGroup()
                .addGroup(customer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout manager_panelLayout = new javax.swing.GroupLayout(manager_panel);
        manager_panel.setLayout(manager_panelLayout);
        manager_panelLayout.setHorizontalGroup(
            manager_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        manager_panelLayout.setVerticalGroup(
            manager_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout state_infoLayout = new javax.swing.GroupLayout(state_info);
        state_info.setLayout(state_infoLayout);
        state_infoLayout.setHorizontalGroup(
            state_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(state_infoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(customer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(manager_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(cashier_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(state_infoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Customer_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Manager_info)
                .addGap(201, 201, 201)
                .addComponent(Cashier_info)
                .addGap(118, 118, 118))
        );
        state_infoLayout.setVerticalGroup(
            state_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(state_infoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(state_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customer_info)
                    .addComponent(Manager_info)
                    .addComponent(Cashier_info))
                .addGap(18, 18, 18)
                .addGroup(state_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manager_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cashier_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(state_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(state_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        permitButton.setText("next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(occ_label, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(start_b, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(suspend_b, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(resume_b, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(stop_b, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(end_b, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movement_label)
                            .addComponent(n_costumers_label))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ncustomers)
                            .addComponent(timeOut_Customers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aviso)
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sto_label)
                            .addComponent(Supervisor_label))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sto_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(supervisor_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(permitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(occ_label)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n_costumers_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Supervisor_label)
                        .addComponent(ncustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aviso))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supervisor_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(permitButton)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movement_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeOut_Customers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sto_label))
                    .addComponent(sto_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(suspend_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(start_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resume_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stop_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(end_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(147, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_bActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_start_bActionPerformed

    private void suspend_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspend_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspend_bActionPerformed

    private void resume_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resume_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resume_bActionPerformed

    private void end_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_bActionPerformed

    //start everything
    private void show_painel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_painel
        // TODO add your handling code here:
        String get_input_n_customers = ncustomers.getText();
        cto = Integer.parseInt(timeOut_Customers.getSelectedItem().toString());
        sto = Integer.parseInt(sto_value.getSelectedItem().toString());
        som = supervisor_value.getSelectedItem().toString();

        if (som.equals("manual")) {
            permitButton.setVisible(true);
        } else {
            permitButton.setVisible(true);
        }

        if (get_input_n_customers.isEmpty()) {
            N_Customers = 10; // default
            System.out.println("Input certo, o valor esta entre 1 e 99, o valor inserido é: " + N_Customers);
            state_info.setVisible(true);
            StringBuilder message = new StringBuilder();
            message.append(N_Customers).append(";").append(cto).append(";").append(som).append(";").append(sto); // send all parameters to OIS
            System.out.println("parameters: " + message);
            try {
                ServerOCC server = new ServerOCC(60013, message.toString());
            } catch (IOException ex) {
                Logger.getLogger(OCC.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            N_Customers = Integer.parseInt(get_input_n_customers);
            if (N_Customers >= 1 && N_Customers <= 99) {
                state_info.setVisible(true);
                ncustomers.setText("");
                aviso.setText("");
                StringBuilder message = new StringBuilder();
                message.append(N_Customers).append(";").append(cto).append(";").append(som).append(";").append(sto); // send all parameters to OIS
                System.out.println("parameters: " + message);
                try {
                    ServerOCC server = new ServerOCC(60013, message.toString());
                } catch (IOException ex) {
                    Logger.getLogger(OCC.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Input errado, tem de estar entre 1 e 99");
                aviso.setText("errado, [1,99]");
                aviso.setVisible(true);
                ncustomers.setText("");
            }
        }
    }//GEN-LAST:event_show_painel

    private void client(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_client
        // TODO add your handling code here:

        try {
            ClientOCC clientocc = new ClientOCC(6003);
            
            //String[] variables = Message.split(";");
            //System.out.println("Message " + Message);
        } catch (IOException ex) {
            Logger.getLogger(OCC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_client

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OCC().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cashier_info;
    private javax.swing.JLabel Customer_info;
    private javax.swing.JLabel Manager_info;
    private javax.swing.JLabel Supervisor_label;
    private javax.swing.JLabel aviso;
    private javax.swing.JPanel cashier_panel;
    private javax.swing.JPanel customer_panel;
    private javax.swing.JButton end_b;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel manager_panel;
    private javax.swing.JLabel movement_label;
    private javax.swing.JLabel n_costumers_label;
    private javax.swing.JTextField ncustomers;
    private javax.swing.JLabel occ_label;
    private javax.swing.JButton permitButton;
    private javax.swing.JButton resume_b;
    private javax.swing.JButton start_b;
    private javax.swing.JPanel state_info;
    private javax.swing.JLabel sto_label;
    private javax.swing.JComboBox<String> sto_value;
    private javax.swing.JButton stop_b;
    private javax.swing.JComboBox<String> supervisor_value;
    private javax.swing.JButton suspend_b;
    private javax.swing.JComboBox<String> timeOut_Customers;
    // End of variables declaration//GEN-END:variables
}
